### ISSUE TITLE
How Wireframe models work? (not a bug, just question)

### ISSUE THREAD

**Issue by verypleasentusername** [blackears/cyclopsLevelBuilder#102]
When i was trying to export cyclops as `.gltf` i made a mistake and exported it through `godot's export scene` menu. In resulted file, for every block, there was a wireframe model that was pure-white. later a found that exporting as `.gltf` was actually supposed to be done through cyclop's menu but at that point i wondered how wireframe was made. So thats the question.
i tried making wireframe model in blender but in godot it didnt have `material` variable i could pass shader to and it generally didnt show up(it might be because model didn't have any faces).
 Is model being `array mesh` type is recuired? And should it be generated through code? 
I dont have trouble with that but it seems kinda weird to me. I couldn't find any quick way to make wireframe models in godot so thats why i'm asking here, sorry if thats shouldn't be here.

**Comment by blackears** [comment]
ArrayMesh is the best way to make meshes at runtime.  It produces the most optimized and flexible models.  It also lets you make things like wireframes and point clouds.  If you want to use the 1.0.2 development version of Cyclops, I've added a command to the menu that lets you export the blocks without including the wireframe.  There isn't really a way to do that using Godot's built in exporter.

**Comment by verypleasentusername** [comment]
> ArrayMesh is the best way to make meshes at runtime. It produces the most optimized and flexible models. It also lets you make things like wireframes and point clouds. If you want to use the 1.0.2 development version of Cyclops, I've added a command to the menu that lets you export the blocks without including the wireframe. There isn't really a way to do that using Godot's built in exporter.

Export command through menu is great, it doesnt have wireframes for everything. but it also doesn't have any collision shapes and occluder nodes which is a big downside of using this way.

**Comment by blackears** [comment]
Why would you want those in the export?  Unless you mean from other nodes?
