### ISSUE TITLE
Implementing Collision Layers and Masks to the Cyclops Level Gen Blocks (Feature Request)

### ISSUE THREAD

**Issue by Corruptinator** [blackears/cyclopsLevelBuilder#103]
This might sound challenging considering that 3D physics is involved, but can by any chance the addon utilize Godot's Collison Layers/Masks?

I realized that Cyclops Level Builder Blocks doesn't have an option to use Collision Layers which is useful for making sure the RayCast for cameras does not clip through. (Just to clarify, the raycast is colliding with the Godot Engine's CSG meshes which does have the Collision Layers/Mask Property, before the Raycast does not collide with the Cyclops Blocks. The Raycast was set on **_Collision Layer/Mask "2"_**.)

https://github.com/blackears/cyclopsLevelBuilder/assets/5027750/ed2743a8-ca72-49e8-b84f-3c0b0c3f0579

**Comment by blackears** [comment]
The CyclopsBlock object does have a field you can use to set both a collision layer and collision mask.  Let me know if this is what you were looking for.

**Comment by Corruptinator** [comment]
Sorry for the non-response @blackears, holidays were busy. I'm having a bit of trouble looking for the field you mentioned.

**Comment by blackears** [comment]
Select your block in the browser and then change the mask in the inspector.  This is only in the 1.0.2 dev version.

![image](https://github.com/blackears/cyclopsLevelBuilder/assets/6724608/2a416ddd-01a7-4352-8600-958c26ac60d4)

**Comment by Corruptinator** [comment]
Ah there it is, thanks! turns out I was using the wrong version.

**Comment by blackears** [comment]
thanks for the suggestion.  I've added the ability to set the collision type in the block, cylinder prism and stairs tools.  For existing blocks, you'll need to select them and change their values in the inspector panel.
