### ISSUE TITLE
Serious conflict with AMD FSR 2.0

### ISSUE THREAD

**Issue by TheNetherPug** [blackears/cyclopsLevelBuilder#107]
I am working on a game and would like to use this addon as a method of creating my levels faster.

However, the very moment I place _any_ material, even new ones, into the material dock, I am bombarded with AMD FSR errors in console until I remove the material.

Unfortunately I cannot remove AMD FSR from my game, as it brings serious performance issues due to the high-level graphics my game provides.

Below is an image. 

Can this issue be rectified, or if it already has, where can I find the dev build?

![image](https://github.com/blackears/cyclopsLevelBuilder/assets/91162221/5c742d24-8699-4e22-87fe-e681c14ccce3)

**Comment by TheNetherPug** [comment]
Update: I have found the solution, the subviewport in material_snapshot.tres had it's scaling set to AMD FSR 2.0, once changed the error no longer persists.

**Comment by TheNetherPug** [comment]
I will be creating a pull request shortly

**Comment by blackears** [comment]
I'm not suer what you mean - that doesn't seem like something you can set the scale to.  But I'm glad you were able to work around this.
