### ISSUE TITLE
State Error message.

### ISSUE THREAD

**Issue by Speedwagen** [blackears/cyclopsLevelBuilder#109]
I was just wondering why I was getting this error message
`Cannot assign a value of type NumbericLineEdit.State to variable "state" with specified type State.`

`Line 77:Invalid operands "State" and "NumbericLineEdit.State" for "==" operator.`

`Line 79:Value of type "NumbericLineEdit.State" cannot be assigned to a variable of type "State".`

`Line 81:Invalid operands "State" and "NumbericLineEdit.State" for "==" operator.`

`Line 84:Value of type "NumbericLineEdit.State" cannot be assigned to a variable of type "State".`

`Line 85:Invalid operands "State" and "NumbericLineEdit.State" for "==" operator.`

`Line 86:Value of type "NumbericLineEdit.State" cannot be assigned to a variable of type "State".`

`Line 93:Invalid operands "State" and "NumbericLineEdit.State" for "==" operator.`

`Line 95:Value of type "NumbericLineEdit.State" cannot be assigned to a variable of type "State".`

`Line 98:Invalid operands "State" and "NumbericLineEdit.State" for "==" operator.`

`Line 121:Value of type "NumbericLineEdit.State" cannot be assigned to a variable of type "State".`

I was trying to make a state machine for my project and this keeps flagging.

![Godot_v4 2-stable_mono_win64_HMoGQjGjVy](https://github.com/blackears/cyclopsLevelBuilder/assets/110987088/930fc41f-6ab5-4303-bbbd-5d2bf1eabe61)

**Comment by blackears** [comment]
I'm guessing you have a class names State somewhere in your project which is causing a conflict.

**Comment by Speedwagen** [comment]
I think that is it. I was trying to make a state machine which I think
caused the conflict

**Comment by Speedwagen** [comment]
I thought I had solved it but now I am getting spammed with `Failed loading resource: res://addons/cyclops_level_builder/docks/uv_editor/uv_editor_preview.gd. Make sure resources have been imported by opening the project in the editor at least once.`

**Comment by blackears** [comment]
Are you using version 1.0.1 or the 1.0.2 dev version?

**Comment by Speedwagen** [comment]
I grabbed it from the master branch. I did upgrade from 1.0.1 I think

**Comment by PolskaPole** [comment]
I have the same issue and for me , i thinkm it's in conflict with the "StateChart"-Addon (https://github.com/derkork/godot-statecharts ) that I'm using. If I go with "Lookup Symbol" on the State enum,  it redirects to the state chart addon which has a class named "State"

**Comment by blackears** [comment]
This was changed.  If you checkout the developer branch, this enum has been renamed,

**Comment by PolskaPole** [comment]
> This was changed. If you checkout the developer branch, this enum has been renamed,

Good to know, thanks. Just downloaded the current release and came across this issue .

**Comment by Gamepro5** [comment]
@blackears Can you also rename the settings class? Something like CyclopsSettings? I had to re-install because I had a settings class in my project beforehand.

**Comment by blackears** [comment]
I've changed the class name in the dev branch.
