### ISSUE TITLE
Display a preview point when creating a prism

### ISSUE THREAD

**Issue by Calinou** [blackears/cyclopsLevelBuilder#11]
- Related to https://github.com/blackears/cyclopsLevelBuilder/issues/10.

When creating a prism, you don't know exactly where each point will be snapped to until you click.

I suggest drawing a translucent yellow sphere to denote the location where the next point will appear when you click, based on the current grid snap distance.

**Comment by blackears** [comment]
This should work now.

**Comment by Calinou** [comment]
Thanks again for the quick turnaround :slightly_smiling_face:
