### ISSUE TITLE
Shortcuts doesn't work :(( [4.2]

### ISSUE THREAD

**Issue by ArsoodLM** [blackears/cyclopsLevelBuilder#119]
First of all, this plugin didn't work at all, and I realized that I had to make an autoload for it, and then I saw that the shortcuts didn't work at all, nothing, officially, nothing, even with the control key, you can't move the faces.

**Comment by blackears** [comment]
I've posted this video.  Try following the steps in the installation section and see if that resolves the issue.

https://youtu.be/mbw_6dnOt_g
