### ISSUE TITLE
Bug: Menu button not loading

### ISSUE THREAD

**Issue by 3mdistal** [blackears/cyclopsLevelBuilder#124]
I'm following the tutorial and properly loading the Autoload, etc. All functionality is there, with no errors in the console.

However, there is no menu button visible in the plugin.

<img width="652" alt="Screenshot 2024-01-17 at 11 06 48 AM" src="https://github.com/blackears/cyclopsLevelBuilder/assets/86723305/ab87bc48-f85b-4ac8-9c5e-6685a8eaced2">

The menu button _is_ visible and there in the code (I went and checked the menu scene), but it doesn't appear in the plugin.

I'm on Godot 4.2.1 stable.

**Comment by 3mdistal** [comment]
I went to the `editor_toolbar.tscn` and gave the Menu button a custom minimum size, for testing purposes. Now, I just see an unclickable gap.

This is on a brand new project, by the way, with Cyclops being the only plugin installed, just to reduce the chance of something interfering.

<img width="1053" alt="Screenshot 2024-01-17 at 11 21 04 AM" src="https://github.com/blackears/cyclopsLevelBuilder/assets/86723305/50e1a09f-9480-4aa2-b7b2-b52ee3d8d954">

I am also now seeing "Can't take value from empty array." occasionally in the console.

**Comment by blackears** [comment]
I don't know why that is happening.  It's just a standard MenuBar control, so it should work.  Maybe there's something strange with your Godot installation?  What OS are you using?  I'm not sure what I might be able to do about this.

The `Can't take value from empty Array.` is being called by Godot from something in the scene graph.  It doesn't provide any further information on what is causing it, so I have little idea where to look to try and debug it.  It doesn't seem to affect the running of Cyclops, though.

**Comment by blackears** [comment]
I just tried again with v4.2.1.stable.official [b09f793f5] and it's displaying properly there too.  Are you running off of a cloned Github branch or off of the zip file from the releases?

**Comment by 3mdistal** [comment]
I did a fresh install of Godot and then cloned the demo project. Same problem.

I'm on an M1 Pro Mac, using v4.2.1.stable.official [b09f793f5] (same as the version you tried).

I have no clue what may be causing this, but happy to screen share specific things that might help you.

<img width="1840" alt="Screenshot 2024-01-18 at 8 21 07 AM" src="https://github.com/blackears/cyclopsLevelBuilder/assets/86723305/21e47e32-ab87-4c03-a187-96ff8e408a2f">

**Comment by keshavagrawal89** [comment]
Getting the same problem. No menu bar. 

Godot 4.2
cyclopsbuilder 1.0.2
Plugin successfully enabled.

**Comment by EmilienLeroy** [comment]
Hi @3mdistal and @keshavagrawal89 
I encountered the same issue and found a workaround to display the menu.

1. Navigate to this file: `editor_toolbar.tscn`

   ![image](https://github.com/blackears/cyclopsLevelBuilder/assets/31723722/858bfbe2-945c-42a9-9c13-a0478d48447f)

2. Select the `MenuBar` node within the file:

   ![image](https://github.com/blackears/cyclopsLevelBuilder/assets/31723722/e90edc50-8ba5-44a8-b8a3-20e2f6266e90)

3. Uncheck the `Prefer Global Menu` option:

   ![image](https://github.com/blackears/cyclopsLevelBuilder/assets/31723722/369c9f8d-c52f-4d06-afe4-bda11faf7415)

4. Save your changes and restart Godot. The menu should now appear:

   ![image](https://github.com/blackears/cyclopsLevelBuilder/assets/31723722/16ec3a6d-f84e-4d2c-8cf6-5c87b5b20f26)

**Comment by EmilienLeroy** [comment]
Hi @blackears 
I have installed the addon from the `master` branch, and it work perfectly for me !

![image](https://github.com/blackears/cyclopsLevelBuilder/assets/31723722/6f2c2807-425b-486d-bab3-0b29848bab44)
