### ISSUE TITLE
'uv_editor_preview.gd' not found

### ISSUE THREAD

**Issue by PangolinMontanari** [blackears/cyclopsLevelBuilder#128]
After installation and activating the plugin, assigning the autoload, I receive these errors in console:

![image](https://github.com/blackears/cyclopsLevelBuilder/assets/145796201/2dfee75f-a340-4f34-8c2b-410a954cdbe7)

Sure enough, there's no /uv_editor/ folder or uv_editor_preview.gd in the repository.

**Comment by blackears** [comment]
What version of Cyclops are you using?  I think that got renamed back in version 1.0.1.  Download the 1.0.2 release from https://github.com/blackears/cyclopsLevelBuilder/releases/tag/v1.0.2

**Comment by blackears** [comment]
That's strange.  That was removed many months ago and doesn't appear in the latest release.  (https://github.com/blackears/cyclopsLevelBuilder/releases/tag/v1.0.2)  Are you sure you're using the latest code?
