### ISSUE TITLE
Errors on file transfer

### ISSUE THREAD

**Issue by gentleboat** [blackears/cyclopsLevelBuilder#129]
When first putting all files into my project, I get the following errors:
  res://addons/cyclops_level_builder/menu/editor_toolbar.gd:169 - Parse Error: Identifier "CyclopsAutoload" not declared in the current scope.
  res://addons/cyclops_level_builder/snapping/snapping_system_grid.gd:36 - Parse Error: Identifier "CyclopsAutoload" not declared in the current scope.
  res://addons/cyclops_level_builder/snapping/snapping_system_grid.gd:55 - Parse Error: Identifier "CyclopsAutoload" not declared in the current scope.
  res://addons/cyclops_level_builder/cyclops_level_builder.gd:-1 - Compile Error: 
  res://addons/cyclops_level_builder/cyclops_level_builder.gd:84 - Parse Error: Identifier "CyclopsAutoload" not declared in the current scope.

**Comment by blackears** [comment]
The CyclopsAutoload need to be present in the Autoloads area to work.  You may also need to restart the project to make sure everything has compiled correctly.  Please have a look at the Installation section: https://github.com/blackears/cyclopsLevelBuilder

**Comment by gentleboat** [comment]
Well those instructions work well and good, and even resolved my issue, but apparently I can't read so I'm upset.

**Comment by blackears** [comment]
I'll close this issue as it sounds like it is solved.  I do plan to work on the Autoload issue, but that will probably have to wait for v1.0.4.
