### ISSUE TITLE
Implement the ability to exclude certain faces from drawing

### ISSUE THREAD

**Issue by Calinou** [blackears/cyclopsLevelBuilder#13]
Right now, all faces are drawn, even if they face other solid objects. This can impact performance in complex levels, especially when using the Forward Mobile rendering method which lacks a depth prepass (which means overdraw is expensive there).

There should be a way to mark certain faces not to be drawn, similar to assigning a `nodraw` texture in GtkRadiant. (The mesh generation should skip those faces entirely, as opposed to using an invisible material.)

Doing this automatically would be nice, but I think it's good to have this as a manual step for now.

**Comment by blackears** [comment]
I've merged code that will let you toggle visibility of faces.  It's in the face properties editor dock.
