### ISSUE TITLE
While editing blocks I can't rightpress+WSAD to move around the scene

### ISSUE THREAD

**Issue by darkhog** [blackears/cyclopsLevelBuilder#132]
Seems like right click is bound to some kind of cancel/undo feature while editing blocks, which prevents me from being able to easily move around the scene with RMB drag+WSAD like I can do while blocks aren't selected. Please fix that.

**Comment by blackears** [comment]
A fix has already been applied to the 1.0.3 dev branch.  You can check that out.  1.0. 3 shout be released in a month or two.

**Comment by darkhog** [comment]
Which branch is it? Is it pr141 or some other one?
