### ISSUE TITLE
Cyclops Level Builder 1.0.2 error on Godot 4.2.1

### ISSUE THREAD

**Issue by Vityy** [blackears/cyclopsLevelBuilder#135]
Hi,

I keep on getting those 3 errors everytime I open my project with Cyclops installed, I followed the enabling process on the github page, tried importing from the ZIP AND the source file and it's always the same

  res://addons/cyclops_level_builder/snapping/snapping_system_grid_properties_editor.gd:46 - Invalid set index 'value' (on base: 'PanelContainer (NumbericLineEdit)') with value of type 'float'.
  res://addons/cyclops_level_builder/snapping/snapping_system_grid_properties_editor.gd:46 - Invalid set index 'value' (on base: 'PanelContainer (NumbericLineEdit)') with value of type 'float'.
  res://addons/cyclops_level_builder/tools/tool_block_settings_editor.gd:42 - Invalid set index 'disabled' (on base: 'PanelContainer (NumbericLineEdit)') with value of type 'bool'.
  res://addons/cyclops_level_builder/controls/vector3_edit.gd:28 - Invalid set index 'value' (on base: 'PanelContainer (NumbericLineEdit)') with value of type 'float'.

The third error happens every frame so it's kind of annoying and disrupts my workflow, could someone help me on this one please?

**Comment by blackears** [comment]
That code has changed.  If you check out the development build, does it still happen?

**Comment by Vityy** [comment]
I juste tried to clone the git repo and try the "master" branch version and it seems that the error message is gone. Thank you for the fast answer :)

**Comment by blackears** [comment]
Glad it's working!
