### ISSUE TITLE
Latest operation always gets undone when right clicking to fly, even if confirmed via unselecting it.

### ISSUE THREAD

**Issue by Gamepro5** [blackears/cyclopsLevelBuilder#138]
https://github.com/blackears/cyclopsLevelBuilder/assets/23440295/2cf9c5b7-07b2-43e2-9109-9fb957d3a551

This is really unintuitive because when I move a block I immediately want to start flying around to see if I like this placement.

**Comment by blackears** [comment]
A fix for this has been checked into the latest development branch.

**Comment by Gamepro5** [comment]
Thanks king!
