### ISSUE TITLE
Depth map or normals wrong on some sides of object

### ISSUE THREAD

**Issue by cg9999** [blackears/cyclopsLevelBuilder#139]
Create a new project in godot 4.2 or 4.3, install cyclops 1.0.2, make a simple cube block. Import material made in Material Maker 1.3 (included in the project zip). 

Apply material to cube. Looking around the cube shows two sides approximately right, but other sides the tiles distort weirdly:

https://github.com/blackears/cyclopsLevelBuilder/assets/98854/da050329-b294-47f3-a4e0-c53957e81845

Sample project:
[buggy.zip](https://github.com/blackears/cyclopsLevelBuilder/files/14522372/buggy.zip)

**Comment by blackears** [comment]
The problems was that the blocks were not generating tangent vectors.  This should be fixed now.
