### ISSUE TITLE
Texture misalignment when using move tool and subdivisions

### ISSUE THREAD

**Issue by cg9999** [blackears/cyclopsLevelBuilder#140]
Not sure if I misunderstand how things should work, but the texture behaviour when using move tool+subdivs seems weird.

Texture moves along with the block. If i instead use the select face tool, followed by A to select all, I get the expected behaviour.

https://github.com/blackears/cyclopsLevelBuilder/assets/98854/21462001-bd00-4ed0-98a1-c716f7d80716

godot 4.2.1 or 4.3 dev with cyclops 1.0.2

Update:

Seems to be due to this block being commented out. Uncommenting makes things work. Not sure why it's disabled...
https://github.com/blackears/cyclopsLevelBuilder/blob/f3168e51008cf9fcf3d7ac9b62dd0336e63d3dd6/godot/addons/cyclops_level_builder/commands/cmd_transform_blocks.gd#L63

**Comment by blackears** [comment]
I think I disabled that when I was changing how commands were being called.  I've restored it now.
