### ISSUE TITLE
Use Godot's transform widgets whenever possible

### ISSUE THREAD

**Issue by darkhog** [blackears/cyclopsLevelBuilder#149]
Now that blocks are regular nodes, why not use standard transform widgets for global block operations (operations that affect the entire block, as opposed to specific face/edge/vertice), with snapping done by Godot itself. The custom widgets could be used for editing particular faces/edges/vertices unless it would be possible to use Godot's standard widgets for that too.

**Comment by blackears** [comment]
Godot's regular widgets are unsuitable since the blocks are being modified when transformed.  Godot's snapping is also not accessible through the API.  I hope to improve the transform gizmos in the future.
