### ISSUE TITLE
Cannot editor move camera in block modifying modes

### ISSUE THREAD

**Issue by CpazR** [blackears/cyclopsLevelBuilder#150]
When any of the following modes are selected:
![2024-03-24 00_45_59-(_) level_0 tscn - bb-godot-prototype - Godot Engine](https://github.com/blackears/cyclopsLevelBuilder/assets/6466091/ed48dafc-1a73-4e9b-bf2e-4b9d91eaf2e1)

The camera cannot be moved.

This is a significant workflow hindrance, especially since there are no hotkeys to swap modes easily (at least none that are clearly documented as far as I could find). Maybe I'm missing something about the intended workflow, but I'm unsure why moving the camera wouldn't be allowed.

**Comment by blackears** [comment]
If you mean the viewport camera, you can middle click and drag to rotate the viewport or shift-middle click drag to pan side to side.  You can also mousewheel to zoom the camera.  All three of these tools are designed to do this and it works for me.  Are you unable to do this?

**Comment by darkhog** [comment]
He meant rightclick+wsad to move around the level (wsad doesn't work with middle click).

**Comment by CpazR** [comment]
> If you mean the viewport camera, you can middle click and drag to rotate the viewport or shift-middle click drag to pan side to side. You can also mousewheel to zoom the camera. All three of these tools are designed to do this and it works for me. Are you unable to do this?

Right, sorry. @darkhog is correct. I'm referring to right clicking and WASD.

**Comment by aranasaurus** [comment]
yeah working on a laptop here... no middle click makes things really difficult :(

**Comment by blackears** [comment]
The tools just pass the middle mouse click along to Godot for navigation.  How are you used to rotating the camera when you're using a laptop?

**Comment by aranasaurus** [comment]
Right click + wasd. Sorry my comment is confusing in retrospect. I meant it was hard to navigate using these tools because I have no middle click. With right click causing the cancellation of the last operation in these tools it's cumbersome to have to exit the tool in order to move the camera, because I don't have the middle click as an option.

**Comment by blackears** [comment]
Sorry about that - I fixed this for the other tools but not the ones @CpazR mentioned.  I just checked in a new fix that addresses this.

**Comment by darkhog** [comment]
Check if the paint materials tool suffer from this issue, just to be sure. Then I think it can be closed. BTW. love the hard work you're putting it to make this tool great. Cheers!

**Comment by blackears** [comment]
Right click fly is working with the other tools too.  I'm going to close this.  Please reopen if you're still having troubles.

**Comment by CpazR** [comment]
This seems to be working mostly well with the new changes. In that it actually accepts this movement. The only question I have is if this is supposed to work more cleanly with the right-click to undo. Because that's still an issue for me.

If not, maybe rebind the undo to require the shift key? Or have the option be toggle-able somehow?

I've been able to make a temporary workaround by simply commenting out the `cmd_xform_blocks.undo_it()` call wherever the "Right click cancel" comment was left. Not a perfect solution, but it works mostly how I would expect.

Curious to know if this is an issue for anyone else or if I'm missing something?

**Comment by blackears** [comment]
My thinking was the you should not be trying to reposition the camera in the middle of an edit operation.  I can understand wanting to right-click fly when you're not actively editing something, but moving the camera when you are could have weird side effects.

**Comment by CpazR** [comment]
Maybe I'm just missing something, but is there a way you're supposed to "finalize" an edit operation without de-selecting and re-selecting the tool? Because in the event I need to make multiple edits to the same mesh, I'll likely need to move the camera too.

> I can understand wanting to right-click fly when you're not actively editing something, but moving the camera when you are could have weird side effects.

Also an aside to this point, so far with my *very* hacky workaround, it doesn't mess anything as far as I can tell.

**Comment by blackears** [comment]
The tool switches between various states as you use it.  When it's in the READY state, it's effectively between operations and safe to fly.  When you're in the middle of dragging something, it isn't.  So as long as you are not currently clicking and dragging a point, you should be able to move around.  The vertex move action is committed every time you release the mouse button.

**Comment by darkhog** [comment]
Except there's still a problem with pressing the RMB undoing your hard work.

**Comment by blackears** [comment]
I've just checked in a change for 1.0.4 so that shouldn't happen any more.
