### ISSUE TITLE
Cone mode for cylinders and a pyramid mode for boxes

### ISSUE THREAD

**Issue by darkhog** [blackears/cyclopsLevelBuilder#153]
Similarly to the tube mode in the cylinder, I think it would be nice to have a cone mode (instead of extruding the circle, it would just make a single vertex on the extrusion point, turning a cylinder into a cone) and similar for boxes, to make pyramidal shapes.

**Comment by blackears** [comment]
I've added a new command to the menu for merging vertices.  Now you can go into vertex mode, select the vertices of one of the faces and merge them at the center to get the tapered shape.
