### ISSUE TITLE
Cyclops level builder install issue on 4.2.1

### ISSUE THREAD

**Issue by warsang** [blackears/cyclopsLevelBuilder#155]
Hi! I'm using Godot v4.2.1 and installed from source the latest cyclops level builder plugin. I added CyclopsAutoload to my autoloads and now when I try to enable the plugin (after restarting the editor), I get:

```
 res://addons/cyclops_level_builder/cyclops_level_builder.gd:73 - Parse Error: Cannot assign a value of type CyclopsLevelBuilder.EditMode to variable "edit_mode" with specified type EditMode.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/cyclops_level_builder/cyclops_level_builder.gd" with error "Parse error". (User)
```

I haven't really changed/done anything else. Am I missing an install step?

**Comment by warsang** [comment]
Looks like changing line 73 from:

`enum EditMode { VERTEX, EDGE, FACE } var edit_mode:EditMode = EditMode.VERTEX
`
to:

`var edit_mode: CyclopsLevelBuilder.EditMode = CyclopsLevelBuilder.EditMode.VERTEX`

removes the error?

**Comment by blackears** [comment]
I've pushed the change.  I'm guessing this is due to a name conflict.
