### ISSUE TITLE
Add a Staircase tool

### ISSUE THREAD

**Issue by Calinou** [blackears/cyclopsLevelBuilder#16]
- Related to https://github.com/blackears/cyclopsLevelBuilder/issues/17.

Add a staircase tool to quickly draw a staircase with a defined step height, which can be set in the toolbar. The number of steps is automatically determined based on the shape's height, and each step's width is also set automatically based on the shape's depth.

Drawing is performed in a similar fashion to the box tool. The staircase's direction is automatically set based on the direction your cursor is moving towards (i.e. the position of the last point relative to the first one).

**Comment by blackears** [comment]
A stairs tool has been added.
