### ISSUE TITLE
Unable to load plugin (4.2.2)

### ISSUE THREAD

**Issue by preacher-online** [blackears/cyclopsLevelBuilder#182]
Cannot load plugin for the life of me, also tried on fresh project. 
Godot: 4.2.2 stable
System: Windows 10 22H2
Cyclops: 1.0.3

"Unable to load addon script from path: 'res://addons/cyclops_level_builder/cyclops_level_builder.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/cyclops_level_builder/plugin.cfg' to prevent further errors."

![image](https://github.com/blackears/cyclopsLevelBuilder/assets/25140342/c6bd5a30-5cbc-45a4-82cd-0e56a791febf)
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/25140342/60702ea0-fd01-4998-8ca8-85553d9c4e2d)

**Comment by preacher-online** [comment]
OK i managed to get it to load by adding to the autoload, but now it's not making any toolbars
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/25140342/7fd035c0-0a7e-4108-87fc-1525cea3076f)

**Comment by darkhog** [comment]
Go to the cyclops tab at the bottom and click "add block". CyclopsBlocks (with an S) should not be used as it is obsolete.

**Comment by preacher-online** [comment]
> Go to the cyclops tab at the bottom and click "add block". CyclopsBlocks (with an S) should not be used as it is obsolete.

that works, thanks. It seems I watched an outdated tutorial.

**Comment by preacher-online** [comment]
> Go to the cyclops tab at the bottom and click "add block". CyclopsBlocks (with an S) should not be used as it is obsolete.

that works, thanks. It seems I watched an outdated tutorial.
