### ISSUE TITLE
Ability to convert just currently selected blocks into godot mesh

### ISSUE THREAD

**Issue by darkhog** [blackears/cyclopsLevelBuilder#185]
Sometimes you want to build your level using the blocks in general, but still need to convert specific blocks to e.g. use it as a base of an Animatable Body 3d to make a moving platform from. Or to use the collision as a collider for Area3D. However the current convert to godot mesh function converts all blocks that are in the scene. An alternative one that only converts the blocks that are selected in the scene tree, would be really appreciated.

**Comment by blackears** [comment]
I've just pushed a change for this.
