### ISSUE TITLE
Move camera to point

### ISSUE THREAD

**Issue by GammaGames** [blackears/cyclopsLevelBuilder#188]
I'm working at scale, and flying around the editor view is very slow. It would be awesome if you could hit a shortcut to place the editor's "center" at a point the mouse touches

**Comment by blackears** [comment]
I wrote some code to do this a while ago.  The problem I'm having is that the Godot editor does not have any way to update the viewport camera.  Even if I overwrite it, the next time the viewport is refreshed, the camera snaps back to where it was before.  I submitted a bug about this a while ago, but don't know if it's ever going to be looked at.

**Comment by GammaGames** [comment]
That's annoying! Maybe I'll write something that drops a node so I can focus and delete it, it'd still be faster than shift flying down the block 🥲

**Comment by darkhog** [comment]
You can change the flying speed by holding right mouse button and using the scroll wheel (scroll wheel up increases the speed, scroll wheel down decreases it). Holding shift also seems to affect the movement speed.

**Comment by GammaGames** [comment]
That makes navigation way easier, thanks!
