### ISSUE TITLE
Unable to load Cyclops - Godot 4.1.1

### ISSUE THREAD

**Issue by enderwraith11** [blackears/cyclopsLevelBuilder#192]
"Unable to load addon script from path: 'res://addons/cyclops_level_builder/cyclops_level_builder.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/cyclops_level_builder/plugin.cfg' to prevent further errors."

` res://addons/cyclops_level_builder/cyclops_level_builder.gd:45 - Parse Error: Could not parse global class "EditorToolbar" from "res://addons/cyclops_level_builder/menu/editor_toolbar.gd".`

I followed the installation tutorial to the T. I renamed the thing to "CyclopsAutoload", i enabled the autoload, i installed the latest version, i even tried this in a separate and fresh project. Every time i try to enable the plugin in the plugins tab i get the above errors and the plugin does not load.

I saw this issue was already raised in another thread, but even after reading that and trying again, i still was not able to load Cyclops.

[EDIT]: Nevermind, I had the wrong version of Cyclops. I didn't realize I had to use version 1.0.1 for Godot 4.1.1
New issue is the cyclops toolbar is not appearing. I get the following error:
`res://addons/cyclops_level_builder/cyclops_level_builder.gd:105 - Invalid set index 'editor_plugin' (on base: 'PanelContainer (EditorToolbar)') with value of type 'EditorPlugin (CyclopsLevelBuilder)'.`

also, apologies if im posting this in a weird way. i never use github so i am not familiar with posting etiquette .

**Comment by blackears** [comment]
It is possible that Cyclops no longer works with 4.1.1 - I've not tested it on that version in a while.  Could you try version 4.3?  

Also, version 1.0.1 is no longer being supported.  I'm not sure why the toolbar is not appearing.  If reloading your project twice is not fixing it, I'd recommend trying the latest version of Cyclops.

**Comment by enderwraith11** [comment]
I just tested a bit now. Latest version of cyclops does not work with my Godot 4.3. project (had to upgrade my project, didn't take long, its not a large project).
I have already tried the latest version of Cyclops on Godot 4.1.1, which also didn't work.
Next I'll try upgrading my 4.1.1 project into 4.2 and not 4.3 and see if that works with the latest version of cyclops.

**Comment by blackears** [comment]
This seems to be due to a problem with the autoloader.  I've checked in a fix, but it's not part of the main branch yet.  /you'll need to pull the move_viewport_rendering branch to see it.

**Comment by blackears** [comment]
I've checked the change into the main branch.  It should work now.

**Comment by enderwraith11** [comment]
Please excuse my github noob-ness here, but when you say "main branch" do you mean the latest release from the releases page?  or do you mean that project display thingy at the top of the main cyclops page? If the latter is the case i genuinely dont know how to download it, theres no "download" button anywhere like what im used to

**Comment by blackears** [comment]
Not one of the releases - you have to download the code directly.  You can do it from the main page

![image](https://github.com/user-attachments/assets/b7a5a0ab-abb8-4c28-b9b8-992ec956b405)
