### ISSUE TITLE
Adding a CyclopsGlobalScene node prints an error

### ISSUE THREAD

**Issue by Calinou** [blackears/cyclopsLevelBuilder#2]
In 4.1.dev d6dde819b, adding a CyclopsGlobalScene node prints an error (regardless of whether the scene already contains a CyclopsBlocks node):

```
Node not found: "ToolInstance3D" (relative to "/root/@EditorNode@15951/@Control@6/@Panel@7/@VBoxContainer@15/@HSplitContainer@18/@HSplitContainer@26/@HSplitContainer@34/@VBoxContainer@35/@VSplitContainer@37/@VSplitContainer@63/@VBoxContainer@64/@PanelContainer@103/MainScreen/@CanvasItemEditor@9121/@VSplitContainer@8948/@HSplitContainer@8950/@HSplitContainer@8952/@Control@8953/@SubViewportContainer@8954/@SubViewport@8955/Node3D/CyclopsGlobalScene").
res://addons/cyclops_level_builder/cyclops_global_scene.gd:59 - Invalid set index 'mesh' (on base: 'null instance') with value of type 'ImmediateMesh'.
```

This error seems to prevent the node from getting its custom icon in the Scene tree dock, even though it's visible in the Create New Node dialog.

The node's functionality seems to work fine in the editor regardless of this error. Running the project will cause a script error.

**Comment by blackears** [comment]
I'm not sure why.  $ToolInstance3D is just a MeshInstance3D that is a child of CyclopsGlobalScene.  I also get no errors using it in Godot 4.0.2, either in the editor or running.  Perhaps this is a bug in 4.1.dev?
