### ISSUE TITLE
Gives out error when selecting vertex insted of grid it gives out error and dosent work, I cant place block after the error and i cant use the vertex i have to use grid and snap 

### ISSUE THREAD

**Issue by prashannathapamagar** [blackears/cyclopsLevelBuilder#203]
res://addons/cyclops_level_builder/snapping/snapping_system_vertex.gd:69 - Invalid access to property or key 'bounds' on a base object of type 'Nil'.

this error is given out anytime i try and place block or edit the blocks it gives the above error after i select the vertex option instead of grid and then the engine keeps on giving the above error until i reload the project.

**Comment by blackears** [comment]
I've checked a fix into the head that should resolve this.  Be aware that I'm currently rewriting a lot of code that deals with UVs, so the current HEAD may not be stable when it comes to UV handling.
