### ISSUE TITLE
Godot fast camera movement interferes with Duplicate hotkey

### ISSUE THREAD

**Issue by Luffaren10** [blackears/cyclopsLevelBuilder#34]
As I'm holding right-click and using WASD to fly around with the camera in Godot, pressing the Shift key to fly faster runs the "Duplicate" hotkey unintentionally, causing all sorts of jank where things get stuck, and i need to press Esc, clear the selection and finally remove the duplicated mesh in order to get back to track.

Could this hotkey be disabled, alternatively having it changed to something different which doesn't collide with the default Godot-editor controls?

**Comment by blackears** [comment]
The hotkey now checks to see if the right mouse button is being held and disables duplication in that case.
