### ISSUE TITLE
Provide scene exporter

### ISSUE THREAD

**Issue by blackears** [blackears/cyclopsLevelBuilder#35]
While Godot will currently allow exporting the scene using Scene/Export As/Gltf, it could be useful to have a more dedicated exporter just for cyclops blocks.

**Comment by blackears** [comment]
Done.

**Comment by blackears** [comment]
I've checked in a fix for the export.

**Comment by x4080** [comment]
Thanks @blackears, is there a plan to release this commit ?

**Comment by blackears** [comment]
I don't know when I'll finally be able to release it, but you can download the main branch and use it,

**Comment by x4080** [comment]
@blackears Thanks
