### ISSUE TITLE
Materials-list does not persist

### ISSUE THREAD

**Issue by Luffaren10** [blackears/cyclopsLevelBuilder#36]
After upgrading to **1.0.1**, all the materials that i've added under the "Materials" tab go away after clicking away (to either the "Uv Transform"/"Tool Properties" tab, or by de-selecting the "CyclopBlocks" node entirely).

I constantly need to re-add the materials manually before being able to assign them to faces with this.
This also happens from creating a brand-new Godot project with a fresh install of the addon, just to confirm.

1) empty:
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/36668214/d8bbf332-9815-4dc6-9a04-6c5ca7df5da7)

2) added some materials:
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/36668214/4bc7450f-0b12-463f-9f67-d2cfa3b7f05b)

3) selected the "Uv Transform" tab, then went back to the "Materials" tab again, now it's all gone:
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/36668214/b50d64be-4bfc-45c5-8bf7-9e659a3ae5d0)

**Comment by blackears** [comment]
I think this is fixed now.  Reopen if you are still having issues.
