### ISSUE TITLE
Add right-click to cancel block shape drawing

### ISSUE THREAD

**Issue by Calinou** [blackears/cyclopsLevelBuilder#4]
Right now, you can use <kbd>Escape</kbd> to cancel shape drawing, but not right mouse button (unlike Blender). I'm pretty used to using right-click to cancel such actions, so I'd like to see this in Cyclops :slightly_smiling_face: 

If you really want to use freelook while shape drawing, use <kbd>Shift + F</kbd> to toggle it. (Note that you won't be able to rotate the camera, only move it.)

**Comment by blackears** [comment]
You can now cancel block drawing with a right click.  I'm not sure what you're referring to with freelook.  Please open a separate issue for this feature.

**Comment by codecat** [comment]
I think this behavior is actually really confusing and generally against how I expect Godot to work, so I'd vote to revert this, as I thought it was a bug at first.
