### ISSUE TITLE
Add Godot version compatibility information to documentation

### ISSUE THREAD

**Issue by toolness** [blackears/cyclopsLevelBuilder#45]
Hi!  I recently learned about this tool through Gamefromscratch and it looks really cool.

However, one of the top questions on my mind is, "What version of Godot is this compatible with?"  Since 4.0 was released relatively recently and introduced a lot of breaking changes, and since the 3.x line is still considered the "LTS" version, it seems valuable to call this out prominently in the documentation somewhere.

(I would just submit a PR to add the docs myself but I don't actually know what versions it supports!)

**Comment by blackears** [comment]
I've updated the docs.  I have no plans to provide a Godot 3 version since there are a lot of breaking changes between the two.  The code would need a lot of rewriting to work on the older version.

**Comment by toolness** [comment]
Awesome, thanks!
