### ISSUE TITLE
Face select completely whitened out

### ISSUE THREAD

**Issue by elvisish** [blackears/cyclopsLevelBuilder#54]
It's unfortunately impossible to use the UV Transform as the actual face is completely whitened out when using face to select:
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/16231628/3675b64e-3317-497d-be06-f4e8d156199c)

**Comment by blackears** [comment]
I'm not sure why that's happening.  I'm not getting it on my end.  The material used is translucent, so maybe you've configured Godot so translucency doesn't work?  Is this happening on all blocks?  Is there something unusual about the material on that block?  

Sometimes restarting Godot will help.  The editor seems to be caching info, and sometimes a clean start can fix problems.

If you're still having problems, please send in a small example that demonstrates the problem and I can have a look at it.

**Comment by elvisish** [comment]
> I'm not sure why that's happening. I'm not getting it on my end. The material used is translucent, so maybe you've configured Godot so translucency doesn't work? Is this happening on all blocks? Is there something unusual about the material on that block?

It's never happened before, and I'm not sure what editor setting might cause that (I haven't changed anything that I can recall).
> 
> Sometimes restarting Godot will help. The editor seems to be caching info, and sometimes a clean start can fix problems.
> 
> If you're still having problems, please send in a small example that demonstrates the problem and I can have a look at it.

I just restarted and updated to latest RC and it's still weird:
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/16231628/ec13495f-9263-46d0-b549-158944551b96)

**Comment by elvisish** [comment]
Here's a test project:
[CyclopsTransparencyBug.zip](https://github.com/blackears/cyclopsLevelBuilder/files/11486950/CyclopsTransparencyBug.zip)

**Comment by blackears** [comment]
I think there's just something weird about the lighting in your scene.  I deleted the world environment and pointed the directional light at the door and now it looks like this:

![image](https://github.com/blackears/cyclopsLevelBuilder/assets/6724608/437531d6-3f22-450d-99e4-ef924b96daff)

Maybe I should adjust the opacity so it isn't so strong.

**Comment by elvisish** [comment]
> I think there's just something weird about the lighting in your scene.  I deleted the world environment and pointed the directional light at the door and now it looks like this:
> 
> 
> 
> ![image](https://github.com/blackears/cyclopsLevelBuilder/assets/6724608/437531d6-3f22-450d-99e4-ef924b96daff)
> 
> 
> 
> Maybe I should adjust the opacity so it isn't so strong.
> 
> 

Which material/script is it? I could change it now to see if it helps.

**Comment by blackears** [comment]
The WorldEnvironment node.  I don't think you've set it up correctly.  I'd delete it and start over.

**Comment by elvisish** [comment]
No, which opacity setting for the face material?

**Comment by elvisish** [comment]
I took out both WorldEnvironment and DirectionalLight and it's still impossible to see:
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/16231628/b11f4d02-f493-4d89-9e1b-8964e3f177b8)

**Comment by elvisish** [comment]
> The default opacity does indeed seem to be very strong, i can barely see what i'm doing.
> 
> I tried changing the albedo alpha color to **15** on:
> 
> * materials/tool_edit_selected_fill_material
> * materials/tool_edit_active_fill_material
> 
> And it's now much easier to work with. Before and after: ![image](https://user-images.githubusercontent.com/36668214/239015068-9099e3db-e6f1-43c2-9885-a1e66f85ac5c.png) ![image](https://user-images.githubusercontent.com/36668214/239014933-05018d91-00fd-4b0b-b2b2-c9a9cb8b32da.png)

Thanks, that's way better, I can actually seen what I'm doing now.

**Comment by blackears** [comment]
I'd already changed the opacity to 96 in the HEAD.  15 is much to translucent to be the general setting in my opinion, but you can adjust it to whatever value you find useful.  The materials @Luffaren10 mentioned are the correct ones.
