### ISSUE TITLE
Get rid of the blue line under the icons

### ISSUE THREAD

**Issue by blackears** [blackears/cyclopsLevelBuilder#58]
The icon bar has a blue line drawn under it.  I  think it has something to do with the PanelContainer that contains all the buttons.  The component needs to be redesigned so that the buttons sit neatly in a row with no extra UI elements appearing behind them or expanding the size of the toolbar.

**Comment by NathanLovato** [comment]
This blue line is from Godot, it's added under every contextual toolbar item (even for built-in nodes). It's part of the limitations you face when using the toolbar, unfortunately. It's not meant to be removed/changed.

Though technically you can always hack your way through and access everything in the editor: once your editor toolbar has been added to the toolbar, call `get_parent()` on it recursively until you find the node with the blue line style and add theme overrides to that node.

**Comment by CollCaz** [comment]
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/62307305/abbac75d-be7e-457b-9199-a84c04509649)


I managed to make it look like this by changing the stylebox background color of the Panel to be the same color as Godot's base color, that hides the blue line and makes it look like the panel is transparent.
however i was not able to access the base color property for some reason so this only works for the default theme
https://github.com/godotengine/godot/issues/68685

would this be an acceptable solution?

**Comment by blackears** [comment]
If it's supposed to be there, I think I'll let it be.  Hiding it so it looks like it isn't there when it is could lead to problems down the line.  Thanks to both of you for looking into this.
