### ISSUE TITLE
Add right-click to remove a point from prism shape drawing

### ISSUE THREAD

**Issue by Calinou** [blackears/cyclopsLevelBuilder#6]
- Related to https://github.com/blackears/cyclopsLevelBuilder/issues/4.

Right now, you can press <kbd>Backspace</kbd> to remove the last drawn point in a prism that isn't finalized yet. This makes it impossible to remove a point that was drawn a while ago when drawing a complex prism, without removing all points that lead to the problematic point beforehand.

Right-clicking a drawn point in prism shape drawing mode should remove the point in question. This can be used to correct mistakes as undo/redo keys don't work here.

Right-clicking far away from a prism point shouldn't do anything, so you can keep using freelook while placing points.

**Comment by blackears** [comment]
This should be working now.
