### ISSUE TITLE
Orthogonal view movements are broken

### ISSUE THREAD

**Issue by cuppajoeman** [blackears/cyclopsLevelBuilder#65]
https://github.com/blackears/cyclopsLevelBuilder/assets/19198104/1a8b7f1b-24e2-4230-9232-2b323e01b5ea

**Comment by blackears** [comment]
Did you mean drawing blocks in orthogonal viewports is broken?  I've just checked in some code that fixes that.

**Comment by blackears** [comment]
This should be working now.
