### ISSUE TITLE
Add double-click on point or within shape to confirm prism shape drawing

### ISSUE THREAD

**Issue by Calinou** [blackears/cyclopsLevelBuilder#7]
- Related to https://github.com/blackears/cyclopsLevelBuilder/issues/4.

Right now, you need to press <kbd>Enter</kbd> to confirm prism shape drawing.  Double-clicking a point or within the shape should confirm the drawing too, so that you don't have to move your hand from the mouse to the keyboard to perform this operation.

**Comment by blackears** [comment]
You can now double click to place a final point and automatically switch to dragging the prism's height.  Double clicking a specific point or inside the base bounds would be a lot more work to implement.
