### ISSUE TITLE
Not compatible with Godot 4.1

### ISSUE THREAD

**Issue by beggarstudios** [blackears/cyclopsLevelBuilder#73]
Is it possible Cyclops Level Builder is not compatible with Godot 4.1? When I import the addon and try to create a block I get the following error:

res://addons/cyclops_level_builder/menu/editor_toolbar.gd:103 - Invalid call. Nonexistent function 'new' in base 'GDScript'.

**Comment by beggarstudios** [comment]
It would seem that calling Toolblock.new() is not the correct way to instantiate a Toolblock

**Comment by blackears** [comment]
I'm using Godot 4.1 for the current development version.  I would expect that the older releases would work in 4.1 too.  Which release are you using?  Also, Godot can have issues when classes are moved or renamed.  Sometimes closing and repoening the project will fix the error.

If you're still having problems, please post the full error message.

**Comment by Hexadotz** [comment]
Are you sure? It works well here

**Comment by beggarstudios** [comment]
Sorry for the late reply, maybe I made a mistake. I'll try it out asap

**Comment by blackears** [comment]
Closing.  Please reopen if you are still having problems.
