### ISSUE TITLE
Textures not importing

### ISSUE THREAD

**Issue by tbfenet1** [blackears/cyclopsLevelBuilder#78]
I drag the textures im using into the texture window like the tutorial but nothing is happening. no textures show up or work.
all it says in console is this
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/137715428/db90f647-4220-4fd1-a554-e461dd64bfef)
Please help

**Comment by blackears** [comment]
That's not a window for textures.  That's for materials.  You need to make materials with textures and then drag those in.

**Comment by blackears** [comment]
Closing.  Please reopen if you are still having problems.

**Comment by nasOS-official** [comment]
How i can make material for it

**Comment by blackears** [comment]
The regular way you make materials in Godot.  The easiest way is to create a StandardMaterial3D and then fill in the fields that you need.  Any Godot 3D material should work.
