### ISSUE TITLE
It messes up when camera is moved.

### ISSUE THREAD

**Issue by XenOdd** [blackears/cyclopsLevelBuilder#80]
https://github.com/blackears/cyclopsLevelBuilder/assets/75040946/49a6b3d2-1ccf-4a47-8132-662c6d55933d

**Comment by blackears** [comment]
I'm not sure why that happened, but these tools have been modified quite a bit for the upcoming 1.0.2 release and this issue may no longer exist.

**Comment by blackears** [comment]
Also, I'm not sure this actually is an error.  You seem to have been quite a far distance from the origin when you drew the block.  I think you may have just misjudged where it was.

**Comment by XenOdd** [comment]
I tried it on a new project and its working fine. Thanks for your time and your awesome tool!
