### ISSUE TITLE
Having to hold "alt" to move blocks up/down conflicts with the standard window manager on modern Linux desktop

### ISSUE THREAD

**Issue by gulagkulak** [blackears/cyclopsLevelBuilder#81]
On Linux Mint (a popular distro based on Debian) and every other Linux desktop I've ever used holding "alt" and click-dragging starts moving the entire window.

So when I use Cyclops and try to move a block up/down, the entire window moves up/down.

Can you either make this behavior configurable (so I can use ctrl instead of alt, for example) or provide the standard visual object movement handles that most other godot objects have?

**Comment by Calinou** [comment]
It's likely feasible to allow using either <kbd>Alt</kbd> or <kbd>Meta</kbd> (Windows key) as a workaround.

**Comment by gulagkulak** [comment]
I ended up changing my window manager key to `Meta` as a workaround.
