### ISSUE TITLE
Expand Material Creation Documentation

### ISSUE THREAD

**Issue by nerd2ninja** [blackears/cyclopsLevelBuilder#85]
The current documentation for adding a texture to surfaces created by cyclops is to click and drop to the materials panel, select the face you want and click the material imported. 

However, .png, .jpeg, and even some .tres files I found from here [godot engine asset library](https://godotengine.org/asset-library/asset?filter=&category=4&godot_version=&cost=&sort=updated) do not have the effect that is expected. 

Please document whatever process is required to map a texture to a cyclops block.

**Comment by blackears** [comment]
I've added tutorial that describes how to make a basic material.

https://github.com/blackears/cyclopsLevelBuilder/blob/master/doc/materials/material_quick_start.md

**Comment by nerd2ninja** [comment]
> I've added tutorial that describes how to make a basic material.
> 
> https://github.com/blackears/cyclopsLevelBuilder/blob/master/doc/materials/material_quick_start.md

Awesome! Thanks. Sorry about my PR. Not trying to promote some other project, it was just the only way I was able to figure it out on my own, but this helps a bunch so thanks again!

**Comment by blackears** [comment]
No problem.  I just denied that PR because I felt it was off topic and while it may be a good project, it ads a lot of unnecessary complexity.
