### ISSUE TITLE
Create material brush tool

### ISSUE THREAD

**Issue by blackears** [blackears/cyclopsLevelBuilder#87]
New tool to simplify applying materials.  Click and drag to assign current material.

**Comment by novhack** [comment]
Hello! Will this tool also allow to paint materials on specific faces?

**Comment by blackears** [comment]
Yes.  If you click on the Individual face checkbox in the tool properties, it will paint individual faces.  The erase option has not been implemented yet.

**Comment by blackears** [comment]
The paint material brush is committed now.
