### ISSUE TITLE
Crash to desktop when moving blocks

### ISSUE THREAD

**Issue by jungaboon** [blackears/cyclopsLevelBuilder#93]
Editor crashes to desktop (no error windows) sometimes when moving blocks around. This often happens when dragging multiple blocks to a new location or duplicating a block with Shift+D and then moving it. The editor will freeze for a second and CTD. Can also sometimes happen when adjusting edges. Happens more frequently as the amount of blocks in the scene increases.

**Comment by blackears** [comment]
Do you have a specific error message produced?  I'm not sure why this would happen, and if it would be related to Cyclops or the Godot editor.

**Comment by blackears** [comment]
This could just be general instability in Godot, but I'll keep an eye out if I can see anything in the addon causing it.
