### ISSUE TITLE
(Cyclops_level_builder File Error) I can't load the addon in engine due to a random bug!

### ISSUE THREAD

**Issue by TheRealFame** [blackears/cyclopsLevelBuilder#99]
I can send full logs of what pops up. The same stuff you see in red, In the console.

![image](https://github.com/blackears/cyclopsLevelBuilder/assets/29516927/29fed594-6aae-467c-bfd2-0a2e6f270ae8)

**Comment by TheRealFame** [comment]
Unable to load addon script from path: 'res://addons/cyclops_level_builder/cyclops_level_builder.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/cyclops_level_builder/plugin.cfg' to prevent further errors.


------------------------------------------


Godot Engine v4.1.2.stable.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
  res://addons/cyclops_level_builder/docks/material_palette/material_snapshot.gd:27 - Parse Error: Class "MaterialShapshot" hides a global script class.
  res://addons/cyclops_level_builder/docks/material_palette/material_thumbnail.gd:26 - Parse Error: Class "MaterialThumbnail" hides a global script class.
  res://addons/cyclops_level_builder/docks/material_palette/material_palette_viewport.gd:26 - Parse Error: Class "MaterialPaletteViewport" hides a global script class.
  res://addons/cyclops_level_builder/docks/material_palette/thumbnail_group.gd:26 - Parse Error: Class "ThumbnailGroup" hides a global script class.
  res://addons/cyclops_level_builder/docks/uv_editor/uv_editor_viewport.gd:26 - Parse Error: Class "UvEdtiorViewport" hides a global script class.
  res://addons/cyclops_level_builder/controls/numeric_line_edit.gd:26 - Parse Error: Class "NumbericLineEdit" hides a global script class.
  res://addons/cyclops_level_builder/docks/uv_editor/uv_editor_preview.gd:26 - Parse Error: Class "UvEditorPreview" hides a global script class.
  res://addons/cyclops_level_builder/docks/uv_editor/uv_editor_preview_studio.gd:26 - Parse Error: Class "UvEditorPreviewStudio" hides a global script class.
  res://addons/cyclops_level_builder/docks/tool_properties/tool_properties_dock.gd:26 - Parse Error: Class "ToolPropertiesDock" hides a global script class.
  res://addons/cyclops_level_builder/menu/editor_toolbar.gd:26 - Parse Error: Class "EditorToolbar" hides a global script class.
  res://addons/cyclops_level_builder/menu/action_popup_menu.gd:26 - Parse Error: Class "ActionPopupMenu" hides a global script class.
  res://addons/cyclops_level_builder/controls/resource_inspector/line_editor_bool.gd:26 - Parse Error: Class "LineEditorBool" hides a global script class.
  res://addons/cyclops_level_builder/controls/resource_inspector/line_editor_int.gd:26 - Parse Error: Class "LineEditorInt" hides a global script class.
  res://addons/cyclops_level_builder/controls/resource_inspector/line_editor_float.gd:26 - Parse Error: Class "LineEditorFloat" hides a global script class.
  res://addons/cyclops_level_builder/controls/resource_inspector/resource_inspector.gd:26 - Parse Error: Class "ResourceInspector" hides a global script class.
  res://addons/cyclops_level_builder/resources/block_data.gd:26 - Parse Error: Class "BlockData" hides a global script class.
  res://addons/cyclops_level_builder/cyclops_level_builder.gd:26 - Parse Error: Class "CyclopsLevelBuilder" hides a global script class.
  core/config/project_settings.cpp:334 - Property not found: editor_plugins/enabled

**Comment by rpgshooter** [comment]
Hello, i can not seems to replicate the error even when on the same version of godot (4.1.2 mono).
Have you tried downloading the src or source from the git and going into the addons folder and copying that to your projects addons folder?
Make sure to un-tick the enabled plugin here before removing the addon:
![Screenshot 2023-11-01 185855](https://github.com/blackears/cyclopsLevelBuilder/assets/64393427/6530fd6e-ce61-410f-9c00-8552d086f164)
then removing the addon from your addons folder,
after you can paste the source version into your addons folder, then re-enabling it.
If the issue persists feel free to send the project files.
Then the error can be looked at more closely.

All the best ~rpg

**Comment by TheRealFame** [comment]
It still seems to be happening after doing this.. Maybe ill try opening a new project without cyclops, Maybe it requires a already provided project.

**Comment by blackears** [comment]
Godot has an issue where it does not register class names correctly the first time you load new code.  You might want to try opening your project, closing it and then opening it again to see if this problem goes away.

**Comment by TheRealFame** [comment]
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/29516927/08dad97e-876a-4437-a803-925d5ee0ca37)
![image](https://github.com/blackears/cyclopsLevelBuilder/assets/29516927/836e4825-d279-4765-85d9-c3122be0dfe3)

The project itself seems to work when i just use that. But- It seems to get soooooo many errors to the point it just crashes. If i can find its log i could paste the starting lines of what it says here. But i think its just how the plugin is built that has made it broken.
(I did what the owner told me to do on my own project too.)

**Comment by rpgshooter** [comment]
Hello again, have you tried loading the addon in a project on 4.1.2, instead of importing to that version?
there may be conflictions in importing the project and in the loading thats causing issues. If i'm not wrong you could export the block arrays to keep the data/things created.
All the best ~rpg

**Comment by TheRealFame** [comment]
> Hello again, have you tried loading the addon in a project on 4.1.2, instead of importing to that version? there may be conflictions in importing the project and in the loading thats causing issues. If i'm not wrong you could export the block arrays to keep the data/things created. All the best ~rpg

Can you please rephrase that to me? I both moved the addon out and added to my own project, And i used the template project provided with the github. (Using godot v4.1.2)

**Comment by rpgshooter** [comment]
Sorry to rephrase that,
It may be an issue with the project file.
again have you tried a blank level with the cyclops addon from scratch?
I have done additional testing and have ruled out import as a cause.
The only other thing would be the project file. and if your referring to the example project there may be an issue that needs to be rsolved with it.
All the best ~rpg

**Comment by rpgshooter** [comment]
As an addendum i might do a pr, with the latest supported version with the project file

**Comment by TheRealFame** [comment]
Just got done. I made a new project just for it, added the plugin and turned it on, As well as copied materials from the original folder from the project to this new project, What i am left with though are still some questions, And confusion on how i'll even set this up on a already working project.

**Comment by blackears** [comment]
The current codebase requires a minimum of Godot 4.1.1 to run.  This was due to the addition of the custom gizmos.
You can also use the current release version of 1.0.1 which works with Godot 4.0.

**Comment by blackears** [comment]
I'm not sure why you're getting those errors.  It looks like you might accidentally have two copies of the addon included?  I'd recommend creating a new project with only the addon and seeing if you can get that to run.

**Comment by TheRealFame** [comment]
> I'm not sure why you're getting those errors. It looks like you might accidentally have two copies of the addon included? I'd recommend creating a new project with only the addon and seeing if you can get that to run.

I did that. I took the addon and added it to the project i was working on. Getting tons of errors and a plugin that just never worked. On this new project though i am still facing a single bug. Making it unable to see my textures, So i can't see how it handles manually modifying the blocks as meshes so things like uv mapping can be used.

**Comment by blackears** [comment]
There could be a name collision between Cyclops and your classes.  GDScript doesn't have namespaces, so if you've named something with the same name as one of my classes that could knock out the whole thing.

Are you getting any error messages from your new project?  Cyclops uses materials, not raw textures.  If you're trying to add textures to the material dock, that won't work.

**Comment by TheRealFame** [comment]
> There could be a name collision between Cyclops and your classes. GDScript doesn't have namespaces, so if you've named something with the same name as one of my classes that could knock out the whole thing.
> 
> Are you getting any error messages from your new project? Cyclops uses materials, not raw textures. If you're trying to add textures to the material dock, that won't work.

Ahh gotcha, Uh- I'll deffo have to check the project errors again, But i will close this issue for now and troubleshoot on my own with the project i already had created. Cause i mainly need to figure out how to use this thing too.. (Like learning how to add doors to the tab above, Or place down props with the level builder.)

**Comment by SkyTuifua** [comment]
Hello friend! I was having this same issue and was able to fix it following the creator's YouTube video: https://www.youtube.com/watch?v=mbw_6dnOt_g&t=50s

the problem was changing the name of the files in Godot's autoload here is what I did:

1: Open Project Settings > Autoload > Select cyclops_global_scene.tscn
2: In Node name change "CyclopsGlobalScene" to "CyclopsAutoload"
3: reload current project.
4: Should work :')

**Comment by TheRealFame** [comment]
Ty for the comment on the situation, While I'm here~ I may as well provide an update! I learned to model in blender, Meaning what I don't need is a level builder/creator. Instead making me transition my focus to terrain! Even then, Others also advised me I probably wouldn't need that too, Because the main inspiration for my levels were flat, But I'm still gonna utilize both, And dump the terrain if it can't be used for background aesthetics or the sort. With that in mind, I'm glad there's a documented fix for this~ Maybe I'll change the issue name to help others..
